import alert_js from './icons/alert.js';
import arrowDown_js from './icons/arrow-down.js';
import arrowLeft_js from './icons/arrow-left.js';
import arrowRight_js from './icons/arrow-right.js';
import arrowSmallDown_js from './icons/arrow-small-down.js';
import arrowSmallLeft_js from './icons/arrow-small-left.js';
import arrowSmallRight_js from './icons/arrow-small-right.js';
import arrowSmallUp_js from './icons/arrow-small-up.js';
import arrowUp_js from './icons/arrow-up.js';
import beaker_js from './icons/beaker.js';
import bell_js from './icons/bell.js';
import bold_js from './icons/bold.js';
import book_js from './icons/book.js';
import bookmark_js from './icons/bookmark.js';
import briefcase_js from './icons/briefcase.js';
import broadcast_js from './icons/broadcast.js';
import browser_js from './icons/browser.js';
import bug_js from './icons/bug.js';
import calendar_js from './icons/calendar.js';
import check_js from './icons/check.js';
import checklist_js from './icons/checklist.js';
import chevronDown_js from './icons/chevron-down.js';
import chevronLeft_js from './icons/chevron-left.js';
import chevronRight_js from './icons/chevron-right.js';
import chevronUp_js from './icons/chevron-up.js';
import circleSlash_js from './icons/circle-slash.js';
import circuitBoard_js from './icons/circuit-board.js';
import clippy_js from './icons/clippy.js';
import clock_js from './icons/clock.js';
import cloudDownload_js from './icons/cloud-download.js';
import cloudUpload_js from './icons/cloud-upload.js';
import code_js from './icons/code.js';
import comment_js from './icons/comment.js';
import commentDiscussion_js from './icons/comment-discussion.js';
import creditCard_js from './icons/credit-card.js';
import dash_js from './icons/dash.js';
import dashboard_js from './icons/dashboard.js';
import database_js from './icons/database.js';
import desktopDownload_js from './icons/desktop-download.js';
import deviceCamera_js from './icons/device-camera.js';
import deviceCameraVideo_js from './icons/device-camera-video.js';
import deviceDesktop_js from './icons/device-desktop.js';
import deviceMobile_js from './icons/device-mobile.js';
import diff_js from './icons/diff.js';
import diffAdded_js from './icons/diff-added.js';
import diffIgnored_js from './icons/diff-ignored.js';
import diffModified_js from './icons/diff-modified.js';
import diffRemoved_js from './icons/diff-removed.js';
import diffRenamed_js from './icons/diff-renamed.js';
import ellipsis_js from './icons/ellipsis.js';
import eye_js from './icons/eye.js';
import file_js from './icons/file.js';
import fileBinary_js from './icons/file-binary.js';
import fileCode_js from './icons/file-code.js';
import fileDirectory_js from './icons/file-directory.js';
import fileMedia_js from './icons/file-media.js';
import filePdf_js from './icons/file-pdf.js';
import fileSubmodule_js from './icons/file-submodule.js';
import fileSymlinkDirectory_js from './icons/file-symlink-directory.js';
import fileSymlinkFile_js from './icons/file-symlink-file.js';
import fileText_js from './icons/file-text.js';
import fileZip_js from './icons/file-zip.js';
import flame_js from './icons/flame.js';
import fold_js from './icons/fold.js';
import gear_js from './icons/gear.js';
import gift_js from './icons/gift.js';
import gist_js from './icons/gist.js';
import gistSecret_js from './icons/gist-secret.js';
import gitBranch_js from './icons/git-branch.js';
import gitCommit_js from './icons/git-commit.js';
import gitCompare_js from './icons/git-compare.js';
import gitMerge_js from './icons/git-merge.js';
import gitPullRequest_js from './icons/git-pull-request.js';
import globe_js from './icons/globe.js';
import grabber_js from './icons/grabber.js';
import graph_js from './icons/graph.js';
import heart_js from './icons/heart.js';
import history_js from './icons/history.js';
import home_js from './icons/home.js';
import horizontalRule_js from './icons/horizontal-rule.js';
import hubot_js from './icons/hubot.js';
import inbox_js from './icons/inbox.js';
import info_js from './icons/info.js';
import issueClosed_js from './icons/issue-closed.js';
import issueOpened_js from './icons/issue-opened.js';
import issueReopened_js from './icons/issue-reopened.js';
import italic_js from './icons/italic.js';
import jersey_js from './icons/jersey.js';
import kebabHorizontal_js from './icons/kebab-horizontal.js';
import kebabVertical_js from './icons/kebab-vertical.js';
import key_js from './icons/key.js';
import keyboard_js from './icons/keyboard.js';
import law_js from './icons/law.js';
import lightBulb_js from './icons/light-bulb.js';
import link_js from './icons/link.js';
import linkExternal_js from './icons/link-external.js';
import listOrdered_js from './icons/list-ordered.js';
import listUnordered_js from './icons/list-unordered.js';
import location_js from './icons/location.js';
import lock_js from './icons/lock.js';
import logoGist_js from './icons/logo-gist.js';
import logoGithub_js from './icons/logo-github.js';
import mail_js from './icons/mail.js';
import mailRead_js from './icons/mail-read.js';
import mailReply_js from './icons/mail-reply.js';
import markGithub_js from './icons/mark-github.js';
import markdown_js from './icons/markdown.js';
import megaphone_js from './icons/megaphone.js';
import mention_js from './icons/mention.js';
import milestone_js from './icons/milestone.js';
import mirror_js from './icons/mirror.js';
import mortarBoard_js from './icons/mortar-board.js';
import mute_js from './icons/mute.js';
import noNewline_js from './icons/no-newline.js';
import note_js from './icons/note.js';
import octoface_js from './icons/octoface.js';
import organization_js from './icons/organization.js';
import package_js from './icons/package.js';
import paintcan_js from './icons/paintcan.js';
import pencil_js from './icons/pencil.js';
import person_js from './icons/person.js';
import pin_js from './icons/pin.js';
import plug_js from './icons/plug.js';
import plus_js from './icons/plus.js';
import plusSmall_js from './icons/plus-small.js';
import primitiveDot_js from './icons/primitive-dot.js';
import primitiveSquare_js from './icons/primitive-square.js';
import project_js from './icons/project.js';
import pulse_js from './icons/pulse.js';
import question_js from './icons/question.js';
import quote_js from './icons/quote.js';
import radioTower_js from './icons/radio-tower.js';
import reply_js from './icons/reply.js';
import repo_js from './icons/repo.js';
import repoClone_js from './icons/repo-clone.js';
import repoForcePush_js from './icons/repo-force-push.js';
import repoForked_js from './icons/repo-forked.js';
import repoPull_js from './icons/repo-pull.js';
import repoPush_js from './icons/repo-push.js';
import rocket_js from './icons/rocket.js';
import rss_js from './icons/rss.js';
import ruby_js from './icons/ruby.js';
import screenFull_js from './icons/screen-full.js';
import screenNormal_js from './icons/screen-normal.js';
import search_js from './icons/search.js';
import server_js from './icons/server.js';
import settings_js from './icons/settings.js';
import shield_js from './icons/shield.js';
import signIn_js from './icons/sign-in.js';
import signOut_js from './icons/sign-out.js';
import smiley_js from './icons/smiley.js';
import squirrel_js from './icons/squirrel.js';
import star_js from './icons/star.js';
import stop_js from './icons/stop.js';
import sync_js from './icons/sync.js';
import tag_js from './icons/tag.js';
import tasklist_js from './icons/tasklist.js';
import telescope_js from './icons/telescope.js';
import terminal_js from './icons/terminal.js';
import textSize_js from './icons/text-size.js';
import threeBars_js from './icons/three-bars.js';
import thumbsdown_js from './icons/thumbsdown.js';
import thumbsup_js from './icons/thumbsup.js';
import tools_js from './icons/tools.js';
import trashcan_js from './icons/trashcan.js';
import triangleDown_js from './icons/triangle-down.js';
import triangleLeft_js from './icons/triangle-left.js';
import triangleRight_js from './icons/triangle-right.js';
import triangleUp_js from './icons/triangle-up.js';
import unfold_js from './icons/unfold.js';
import unmute_js from './icons/unmute.js';
import unverified_js from './icons/unverified.js';
import verified_js from './icons/verified.js';
import versions_js from './icons/versions.js';
import watch_js from './icons/watch.js';
import x_js from './icons/x.js';
import zap_js from './icons/zap.js';



export { alert } from '/data/github/hiendv/octicons-modular/src/icons/alert.js';
export { arrowDown } from '/data/github/hiendv/octicons-modular/src/icons/arrow-down.js';
export { arrowLeft } from '/data/github/hiendv/octicons-modular/src/icons/arrow-left.js';
export { arrowRight } from '/data/github/hiendv/octicons-modular/src/icons/arrow-right.js';
export { arrowSmallDown } from '/data/github/hiendv/octicons-modular/src/icons/arrow-small-down.js';
export { arrowSmallLeft } from '/data/github/hiendv/octicons-modular/src/icons/arrow-small-left.js';
export { arrowSmallRight } from '/data/github/hiendv/octicons-modular/src/icons/arrow-small-right.js';
export { arrowSmallUp } from '/data/github/hiendv/octicons-modular/src/icons/arrow-small-up.js';
export { arrowUp } from '/data/github/hiendv/octicons-modular/src/icons/arrow-up.js';
export { beaker } from '/data/github/hiendv/octicons-modular/src/icons/beaker.js';
export { bell } from '/data/github/hiendv/octicons-modular/src/icons/bell.js';
export { bold } from '/data/github/hiendv/octicons-modular/src/icons/bold.js';
export { book } from '/data/github/hiendv/octicons-modular/src/icons/book.js';
export { bookmark } from '/data/github/hiendv/octicons-modular/src/icons/bookmark.js';
export { briefcase } from '/data/github/hiendv/octicons-modular/src/icons/briefcase.js';
export { broadcast } from '/data/github/hiendv/octicons-modular/src/icons/broadcast.js';
export { browser } from '/data/github/hiendv/octicons-modular/src/icons/browser.js';
export { bug } from '/data/github/hiendv/octicons-modular/src/icons/bug.js';
export { calendar } from '/data/github/hiendv/octicons-modular/src/icons/calendar.js';
export { check } from '/data/github/hiendv/octicons-modular/src/icons/check.js';
export { checklist } from '/data/github/hiendv/octicons-modular/src/icons/checklist.js';
export { chevronDown } from '/data/github/hiendv/octicons-modular/src/icons/chevron-down.js';
export { chevronLeft } from '/data/github/hiendv/octicons-modular/src/icons/chevron-left.js';
export { chevronRight } from '/data/github/hiendv/octicons-modular/src/icons/chevron-right.js';
export { chevronUp } from '/data/github/hiendv/octicons-modular/src/icons/chevron-up.js';
export { circleSlash } from '/data/github/hiendv/octicons-modular/src/icons/circle-slash.js';
export { circuitBoard } from '/data/github/hiendv/octicons-modular/src/icons/circuit-board.js';
export { clippy } from '/data/github/hiendv/octicons-modular/src/icons/clippy.js';
export { clock } from '/data/github/hiendv/octicons-modular/src/icons/clock.js';
export { cloudDownload } from '/data/github/hiendv/octicons-modular/src/icons/cloud-download.js';
export { cloudUpload } from '/data/github/hiendv/octicons-modular/src/icons/cloud-upload.js';
export { code } from '/data/github/hiendv/octicons-modular/src/icons/code.js';
export { comment } from '/data/github/hiendv/octicons-modular/src/icons/comment.js';
export { commentDiscussion } from '/data/github/hiendv/octicons-modular/src/icons/comment-discussion.js';
export { creditCard } from '/data/github/hiendv/octicons-modular/src/icons/credit-card.js';
export { dash } from '/data/github/hiendv/octicons-modular/src/icons/dash.js';
export { dashboard } from '/data/github/hiendv/octicons-modular/src/icons/dashboard.js';
export { database } from '/data/github/hiendv/octicons-modular/src/icons/database.js';
export { desktopDownload } from '/data/github/hiendv/octicons-modular/src/icons/desktop-download.js';
export { deviceCamera } from '/data/github/hiendv/octicons-modular/src/icons/device-camera.js';
export { deviceCameraVideo } from '/data/github/hiendv/octicons-modular/src/icons/device-camera-video.js';
export { deviceDesktop } from '/data/github/hiendv/octicons-modular/src/icons/device-desktop.js';
export { deviceMobile } from '/data/github/hiendv/octicons-modular/src/icons/device-mobile.js';
export { diff } from '/data/github/hiendv/octicons-modular/src/icons/diff.js';
export { diffAdded } from '/data/github/hiendv/octicons-modular/src/icons/diff-added.js';
export { diffIgnored } from '/data/github/hiendv/octicons-modular/src/icons/diff-ignored.js';
export { diffModified } from '/data/github/hiendv/octicons-modular/src/icons/diff-modified.js';
export { diffRemoved } from '/data/github/hiendv/octicons-modular/src/icons/diff-removed.js';
export { diffRenamed } from '/data/github/hiendv/octicons-modular/src/icons/diff-renamed.js';
export { ellipsis } from '/data/github/hiendv/octicons-modular/src/icons/ellipsis.js';
export { eye } from '/data/github/hiendv/octicons-modular/src/icons/eye.js';
export { file } from '/data/github/hiendv/octicons-modular/src/icons/file.js';
export { fileBinary } from '/data/github/hiendv/octicons-modular/src/icons/file-binary.js';
export { fileCode } from '/data/github/hiendv/octicons-modular/src/icons/file-code.js';
export { fileDirectory } from '/data/github/hiendv/octicons-modular/src/icons/file-directory.js';
export { fileMedia } from '/data/github/hiendv/octicons-modular/src/icons/file-media.js';
export { filePdf } from '/data/github/hiendv/octicons-modular/src/icons/file-pdf.js';
export { fileSubmodule } from '/data/github/hiendv/octicons-modular/src/icons/file-submodule.js';
export { fileSymlinkDirectory } from '/data/github/hiendv/octicons-modular/src/icons/file-symlink-directory.js';
export { fileSymlinkFile } from '/data/github/hiendv/octicons-modular/src/icons/file-symlink-file.js';
export { fileText } from '/data/github/hiendv/octicons-modular/src/icons/file-text.js';
export { fileZip } from '/data/github/hiendv/octicons-modular/src/icons/file-zip.js';
export { flame } from '/data/github/hiendv/octicons-modular/src/icons/flame.js';
export { fold } from '/data/github/hiendv/octicons-modular/src/icons/fold.js';
export { gear } from '/data/github/hiendv/octicons-modular/src/icons/gear.js';
export { gift } from '/data/github/hiendv/octicons-modular/src/icons/gift.js';
export { gist } from '/data/github/hiendv/octicons-modular/src/icons/gist.js';
export { gistSecret } from '/data/github/hiendv/octicons-modular/src/icons/gist-secret.js';
export { gitBranch } from '/data/github/hiendv/octicons-modular/src/icons/git-branch.js';
export { gitCommit } from '/data/github/hiendv/octicons-modular/src/icons/git-commit.js';
export { gitCompare } from '/data/github/hiendv/octicons-modular/src/icons/git-compare.js';
export { gitMerge } from '/data/github/hiendv/octicons-modular/src/icons/git-merge.js';
export { gitPullRequest } from '/data/github/hiendv/octicons-modular/src/icons/git-pull-request.js';
export { globe } from '/data/github/hiendv/octicons-modular/src/icons/globe.js';
export { grabber } from '/data/github/hiendv/octicons-modular/src/icons/grabber.js';
export { graph } from '/data/github/hiendv/octicons-modular/src/icons/graph.js';
export { heart } from '/data/github/hiendv/octicons-modular/src/icons/heart.js';
export { history } from '/data/github/hiendv/octicons-modular/src/icons/history.js';
export { home } from '/data/github/hiendv/octicons-modular/src/icons/home.js';
export { horizontalRule } from '/data/github/hiendv/octicons-modular/src/icons/horizontal-rule.js';
export { hubot } from '/data/github/hiendv/octicons-modular/src/icons/hubot.js';
export { inbox } from '/data/github/hiendv/octicons-modular/src/icons/inbox.js';
export { info } from '/data/github/hiendv/octicons-modular/src/icons/info.js';
export { issueClosed } from '/data/github/hiendv/octicons-modular/src/icons/issue-closed.js';
export { issueOpened } from '/data/github/hiendv/octicons-modular/src/icons/issue-opened.js';
export { issueReopened } from '/data/github/hiendv/octicons-modular/src/icons/issue-reopened.js';
export { italic } from '/data/github/hiendv/octicons-modular/src/icons/italic.js';
export { jersey } from '/data/github/hiendv/octicons-modular/src/icons/jersey.js';
export { kebabHorizontal } from '/data/github/hiendv/octicons-modular/src/icons/kebab-horizontal.js';
export { kebabVertical } from '/data/github/hiendv/octicons-modular/src/icons/kebab-vertical.js';
export { key } from '/data/github/hiendv/octicons-modular/src/icons/key.js';
export { keyboard } from '/data/github/hiendv/octicons-modular/src/icons/keyboard.js';
export { law } from '/data/github/hiendv/octicons-modular/src/icons/law.js';
export { lightBulb } from '/data/github/hiendv/octicons-modular/src/icons/light-bulb.js';
export { link } from '/data/github/hiendv/octicons-modular/src/icons/link.js';
export { linkExternal } from '/data/github/hiendv/octicons-modular/src/icons/link-external.js';
export { listOrdered } from '/data/github/hiendv/octicons-modular/src/icons/list-ordered.js';
export { listUnordered } from '/data/github/hiendv/octicons-modular/src/icons/list-unordered.js';
export { location } from '/data/github/hiendv/octicons-modular/src/icons/location.js';
export { lock } from '/data/github/hiendv/octicons-modular/src/icons/lock.js';
export { logoGist } from '/data/github/hiendv/octicons-modular/src/icons/logo-gist.js';
export { logoGithub } from '/data/github/hiendv/octicons-modular/src/icons/logo-github.js';
export { mail } from '/data/github/hiendv/octicons-modular/src/icons/mail.js';
export { mailRead } from '/data/github/hiendv/octicons-modular/src/icons/mail-read.js';
export { mailReply } from '/data/github/hiendv/octicons-modular/src/icons/mail-reply.js';
export { markGithub } from '/data/github/hiendv/octicons-modular/src/icons/mark-github.js';
export { markdown } from '/data/github/hiendv/octicons-modular/src/icons/markdown.js';
export { megaphone } from '/data/github/hiendv/octicons-modular/src/icons/megaphone.js';
export { mention } from '/data/github/hiendv/octicons-modular/src/icons/mention.js';
export { milestone } from '/data/github/hiendv/octicons-modular/src/icons/milestone.js';
export { mirror } from '/data/github/hiendv/octicons-modular/src/icons/mirror.js';
export { mortarBoard } from '/data/github/hiendv/octicons-modular/src/icons/mortar-board.js';
export { mute } from '/data/github/hiendv/octicons-modular/src/icons/mute.js';
export { noNewline } from '/data/github/hiendv/octicons-modular/src/icons/no-newline.js';
export { note } from '/data/github/hiendv/octicons-modular/src/icons/note.js';
export { octoface } from '/data/github/hiendv/octicons-modular/src/icons/octoface.js';
export { organization } from '/data/github/hiendv/octicons-modular/src/icons/organization.js';
export { package } from '/data/github/hiendv/octicons-modular/src/icons/package.js';
export { paintcan } from '/data/github/hiendv/octicons-modular/src/icons/paintcan.js';
export { pencil } from '/data/github/hiendv/octicons-modular/src/icons/pencil.js';
export { person } from '/data/github/hiendv/octicons-modular/src/icons/person.js';
export { pin } from '/data/github/hiendv/octicons-modular/src/icons/pin.js';
export { plug } from '/data/github/hiendv/octicons-modular/src/icons/plug.js';
export { plus } from '/data/github/hiendv/octicons-modular/src/icons/plus.js';
export { plusSmall } from '/data/github/hiendv/octicons-modular/src/icons/plus-small.js';
export { primitiveDot } from '/data/github/hiendv/octicons-modular/src/icons/primitive-dot.js';
export { primitiveSquare } from '/data/github/hiendv/octicons-modular/src/icons/primitive-square.js';
export { project } from '/data/github/hiendv/octicons-modular/src/icons/project.js';
export { pulse } from '/data/github/hiendv/octicons-modular/src/icons/pulse.js';
export { question } from '/data/github/hiendv/octicons-modular/src/icons/question.js';
export { quote } from '/data/github/hiendv/octicons-modular/src/icons/quote.js';
export { radioTower } from '/data/github/hiendv/octicons-modular/src/icons/radio-tower.js';
export { reply } from '/data/github/hiendv/octicons-modular/src/icons/reply.js';
export { repo } from '/data/github/hiendv/octicons-modular/src/icons/repo.js';
export { repoClone } from '/data/github/hiendv/octicons-modular/src/icons/repo-clone.js';
export { repoForcePush } from '/data/github/hiendv/octicons-modular/src/icons/repo-force-push.js';
export { repoForked } from '/data/github/hiendv/octicons-modular/src/icons/repo-forked.js';
export { repoPull } from '/data/github/hiendv/octicons-modular/src/icons/repo-pull.js';
export { repoPush } from '/data/github/hiendv/octicons-modular/src/icons/repo-push.js';
export { rocket } from '/data/github/hiendv/octicons-modular/src/icons/rocket.js';
export { rss } from '/data/github/hiendv/octicons-modular/src/icons/rss.js';
export { ruby } from '/data/github/hiendv/octicons-modular/src/icons/ruby.js';
export { screenFull } from '/data/github/hiendv/octicons-modular/src/icons/screen-full.js';
export { screenNormal } from '/data/github/hiendv/octicons-modular/src/icons/screen-normal.js';
export { search } from '/data/github/hiendv/octicons-modular/src/icons/search.js';
export { server } from '/data/github/hiendv/octicons-modular/src/icons/server.js';
export { settings } from '/data/github/hiendv/octicons-modular/src/icons/settings.js';
export { shield } from '/data/github/hiendv/octicons-modular/src/icons/shield.js';
export { signIn } from '/data/github/hiendv/octicons-modular/src/icons/sign-in.js';
export { signOut } from '/data/github/hiendv/octicons-modular/src/icons/sign-out.js';
export { smiley } from '/data/github/hiendv/octicons-modular/src/icons/smiley.js';
export { squirrel } from '/data/github/hiendv/octicons-modular/src/icons/squirrel.js';
export { star } from '/data/github/hiendv/octicons-modular/src/icons/star.js';
export { stop } from '/data/github/hiendv/octicons-modular/src/icons/stop.js';
export { sync } from '/data/github/hiendv/octicons-modular/src/icons/sync.js';
export { tag } from '/data/github/hiendv/octicons-modular/src/icons/tag.js';
export { tasklist } from '/data/github/hiendv/octicons-modular/src/icons/tasklist.js';
export { telescope } from '/data/github/hiendv/octicons-modular/src/icons/telescope.js';
export { terminal } from '/data/github/hiendv/octicons-modular/src/icons/terminal.js';
export { textSize } from '/data/github/hiendv/octicons-modular/src/icons/text-size.js';
export { threeBars } from '/data/github/hiendv/octicons-modular/src/icons/three-bars.js';
export { thumbsdown } from '/data/github/hiendv/octicons-modular/src/icons/thumbsdown.js';
export { thumbsup } from '/data/github/hiendv/octicons-modular/src/icons/thumbsup.js';
export { tools } from '/data/github/hiendv/octicons-modular/src/icons/tools.js';
export { trashcan } from '/data/github/hiendv/octicons-modular/src/icons/trashcan.js';
export { triangleDown } from '/data/github/hiendv/octicons-modular/src/icons/triangle-down.js';
export { triangleLeft } from '/data/github/hiendv/octicons-modular/src/icons/triangle-left.js';
export { triangleRight } from '/data/github/hiendv/octicons-modular/src/icons/triangle-right.js';
export { triangleUp } from '/data/github/hiendv/octicons-modular/src/icons/triangle-up.js';
export { unfold } from '/data/github/hiendv/octicons-modular/src/icons/unfold.js';
export { unmute } from '/data/github/hiendv/octicons-modular/src/icons/unmute.js';
export { unverified } from '/data/github/hiendv/octicons-modular/src/icons/unverified.js';
export { verified } from '/data/github/hiendv/octicons-modular/src/icons/verified.js';
export { versions } from '/data/github/hiendv/octicons-modular/src/icons/versions.js';
export { watch } from '/data/github/hiendv/octicons-modular/src/icons/watch.js';
export { x } from '/data/github/hiendv/octicons-modular/src/icons/x.js';
export { zap } from '/data/github/hiendv/octicons-modular/src/icons/zap.js';
