import plus$ from './icons/plus.js';
export { default as plus } from './icons/plus.js';
import primitiveDot$ from './icons/primitive-dot.js';
export { default as primitiveDot } from './icons/primitive-dot.js';
import primitiveSquare$ from './icons/primitive-square.js';
export { default as primitiveSquare } from './icons/primitive-square.js';
import quote$ from './icons/quote.js';
export { default as quote } from './icons/quote.js';
import threeBars$ from './icons/three-bars.js';
export { default as threeBars } from './icons/three-bars.js';
import triangleDown$ from './icons/triangle-down.js';
export { default as triangleDown } from './icons/triangle-down.js';
import triangleLeft$ from './icons/triangle-left.js';
export { default as triangleLeft } from './icons/triangle-left.js';
import triangleRight$ from './icons/triangle-right.js';
export { default as triangleRight } from './icons/triangle-right.js';
import triangleUp$ from './icons/triangle-up.js';
export { default as triangleUp } from './icons/triangle-up.js';
import kebabHorizontal$ from './icons/kebab-horizontal.js';
export { default as kebabHorizontal } from './icons/kebab-horizontal.js';
import kebabVertical$ from './icons/kebab-vertical.js';
export { default as kebabVertical } from './icons/kebab-vertical.js';
import screenFull$ from './icons/screen-full.js';
export { default as screenFull } from './icons/screen-full.js';
import screenNormal$ from './icons/screen-normal.js';
export { default as screenNormal } from './icons/screen-normal.js';
import x$ from './icons/x.js';
export { default as x } from './icons/x.js';
import grabber$ from './icons/grabber.js';
export { default as grabber } from './icons/grabber.js';
import plusSmall$ from './icons/plus-small.js';
export { default as plusSmall } from './icons/plus-small.js';
import pulse$ from './icons/pulse.js';
export { default as pulse } from './icons/pulse.js';
import star$ from './icons/star.js';
export { default as star } from './icons/star.js';
import stop$ from './icons/stop.js';
export { default as stop } from './icons/stop.js';
import sync$ from './icons/sync.js';
export { default as sync } from './icons/sync.js';
import textSize$ from './icons/text-size.js';
export { default as textSize } from './icons/text-size.js';
import report$ from './icons/report.js';
export { default as report } from './icons/report.js';
import linkExternal$ from './icons/link-external.js';
export { default as linkExternal } from './icons/link-external.js';
import checklist$ from './icons/checklist.js';
export { default as checklist } from './icons/checklist.js';
import cloudDownload$ from './icons/cloud-download.js';
export { default as cloudDownload } from './icons/cloud-download.js';
import cloudUpload$ from './icons/cloud-upload.js';
export { default as cloudUpload } from './icons/cloud-upload.js';
import foldUp$ from './icons/fold-up.js';
export { default as foldUp } from './icons/fold-up.js';
import foldDown$ from './icons/fold-down.js';
export { default as foldDown } from './icons/fold-down.js';
import fold$ from './icons/fold.js';
export { default as fold } from './icons/fold.js';
import tasklist$ from './icons/tasklist.js';
export { default as tasklist } from './icons/tasklist.js';
import history$ from './icons/history.js';
export { default as history } from './icons/history.js';
import dash$ from './icons/dash.js';
export { default as dash } from './icons/dash.js';
import listOrdered$ from './icons/list-ordered.js';
export { default as listOrdered } from './icons/list-ordered.js';
import listUnordered$ from './icons/list-unordered.js';
export { default as listUnordered } from './icons/list-unordered.js';
import reply$ from './icons/reply.js';
export { default as reply } from './icons/reply.js';
import mute$ from './icons/mute.js';
export { default as mute } from './icons/mute.js';
import commentDiscussion$ from './icons/comment-discussion.js';
export { default as commentDiscussion } from './icons/comment-discussion.js';
import comment$ from './icons/comment.js';
export { default as comment } from './icons/comment.js';
import ellipsis$ from './icons/ellipsis.js';
export { default as ellipsis } from './icons/ellipsis.js';
import heart$ from './icons/heart.js';
export { default as heart } from './icons/heart.js';
import horizontalRule$ from './icons/horizontal-rule.js';
export { default as horizontalRule } from './icons/horizontal-rule.js';
import info$ from './icons/info.js';
export { default as info } from './icons/info.js';
import italic$ from './icons/italic.js';
export { default as italic } from './icons/italic.js';
import unverified$ from './icons/unverified.js';
export { default as unverified } from './icons/unverified.js';
import verified$ from './icons/verified.js';
export { default as verified } from './icons/verified.js';
import question$ from './icons/question.js';
export { default as question } from './icons/question.js';
import unfold$ from './icons/unfold.js';
export { default as unfold } from './icons/unfold.js';
import signIn$ from './icons/sign-in.js';
export { default as signIn } from './icons/sign-in.js';
import signOut$ from './icons/sign-out.js';
export { default as signOut } from './icons/sign-out.js';
import alert$ from './icons/alert.js';
export { default as alert } from './icons/alert.js';
import arrowDown$ from './icons/arrow-down.js';
export { default as arrowDown } from './icons/arrow-down.js';
import arrowLeft$ from './icons/arrow-left.js';
export { default as arrowLeft } from './icons/arrow-left.js';
import arrowRight$ from './icons/arrow-right.js';
export { default as arrowRight } from './icons/arrow-right.js';
import arrowUp$ from './icons/arrow-up.js';
export { default as arrowUp } from './icons/arrow-up.js';
import arrowBoth$ from './icons/arrow-both.js';
export { default as arrowBoth } from './icons/arrow-both.js';
import arrowSmallDown$ from './icons/arrow-small-down.js';
export { default as arrowSmallDown } from './icons/arrow-small-down.js';
import arrowSmallLeft$ from './icons/arrow-small-left.js';
export { default as arrowSmallLeft } from './icons/arrow-small-left.js';
import arrowSmallRight$ from './icons/arrow-small-right.js';
export { default as arrowSmallRight } from './icons/arrow-small-right.js';
import arrowSmallUp$ from './icons/arrow-small-up.js';
export { default as arrowSmallUp } from './icons/arrow-small-up.js';
import check$ from './icons/check.js';
export { default as check } from './icons/check.js';
import chevronDown$ from './icons/chevron-down.js';
export { default as chevronDown } from './icons/chevron-down.js';
import chevronLeft$ from './icons/chevron-left.js';
export { default as chevronLeft } from './icons/chevron-left.js';
import chevronRight$ from './icons/chevron-right.js';
export { default as chevronRight } from './icons/chevron-right.js';
import chevronUp$ from './icons/chevron-up.js';
export { default as chevronUp } from './icons/chevron-up.js';
import circleSlash$ from './icons/circle-slash.js';
export { default as circleSlash } from './icons/circle-slash.js';
import bold$ from './icons/bold.js';
export { default as bold } from './icons/bold.js';
import mention$ from './icons/mention.js';
export { default as mention } from './icons/mention.js';
import beaker$ from './icons/beaker.js';
export { default as beaker } from './icons/beaker.js';
import bell$ from './icons/bell.js';
export { default as bell } from './icons/bell.js';
import briefcase$ from './icons/briefcase.js';
export { default as briefcase } from './icons/briefcase.js';
import creditCard$ from './icons/credit-card.js';
export { default as creditCard } from './icons/credit-card.js';
import deviceCameraVideo$ from './icons/device-camera-video.js';
export { default as deviceCameraVideo } from './icons/device-camera-video.js';
import deviceCamera$ from './icons/device-camera.js';
export { default as deviceCamera } from './icons/device-camera.js';
import deviceDesktop$ from './icons/device-desktop.js';
export { default as deviceDesktop } from './icons/device-desktop.js';
import deviceMobile$ from './icons/device-mobile.js';
export { default as deviceMobile } from './icons/device-mobile.js';
import gift$ from './icons/gift.js';
export { default as gift } from './icons/gift.js';
import gear$ from './icons/gear.js';
export { default as gear } from './icons/gear.js';
import book$ from './icons/book.js';
export { default as book } from './icons/book.js';
import tag$ from './icons/tag.js';
export { default as tag } from './icons/tag.js';
import telescope$ from './icons/telescope.js';
export { default as telescope } from './icons/telescope.js';
import tools$ from './icons/tools.js';
export { default as tools } from './icons/tools.js';
import trashcan$ from './icons/trashcan.js';
export { default as trashcan } from './icons/trashcan.js';
import unmute$ from './icons/unmute.js';
export { default as unmute } from './icons/unmute.js';
import watch$ from './icons/watch.js';
export { default as watch } from './icons/watch.js';
import key$ from './icons/key.js';
export { default as key } from './icons/key.js';
import archive$ from './icons/archive.js';
export { default as archive } from './icons/archive.js';
import lightBulb$ from './icons/light-bulb.js';
export { default as lightBulb } from './icons/light-bulb.js';
import link$ from './icons/link.js';
export { default as link } from './icons/link.js';
import location$ from './icons/location.js';
export { default as location } from './icons/location.js';
import lock$ from './icons/lock.js';
export { default as lock } from './icons/lock.js';
import mailRead$ from './icons/mail-read.js';
export { default as mailRead } from './icons/mail-read.js';
import mail$ from './icons/mail.js';
export { default as mail } from './icons/mail.js';
import megaphone$ from './icons/megaphone.js';
export { default as megaphone } from './icons/megaphone.js';
import bookmark$ from './icons/bookmark.js';
export { default as bookmark } from './icons/bookmark.js';
import calendar$ from './icons/calendar.js';
export { default as calendar } from './icons/calendar.js';
import clippy$ from './icons/clippy.js';
export { default as clippy } from './icons/clippy.js';
import clock$ from './icons/clock.js';
export { default as clock } from './icons/clock.js';
import desktopDownload$ from './icons/desktop-download.js';
export { default as desktopDownload } from './icons/desktop-download.js';
import globe$ from './icons/globe.js';
export { default as globe } from './icons/globe.js';
import home$ from './icons/home.js';
export { default as home } from './icons/home.js';
import inbox$ from './icons/inbox.js';
export { default as inbox } from './icons/inbox.js';
import law$ from './icons/law.js';
export { default as law } from './icons/law.js';
import milestone$ from './icons/milestone.js';
export { default as milestone } from './icons/milestone.js';
import mortarBoard$ from './icons/mortar-board.js';
export { default as mortarBoard } from './icons/mortar-board.js';
import package$ from './icons/package.js';
export { default as package } from './icons/package.js';
import pencil$ from './icons/pencil.js';
export { default as pencil } from './icons/pencil.js';
import pin$ from './icons/pin.js';
export { default as pin } from './icons/pin.js';
import plug$ from './icons/plug.js';
export { default as plug } from './icons/plug.js';
import rocket$ from './icons/rocket.js';
export { default as rocket } from './icons/rocket.js';
import search$ from './icons/search.js';
export { default as search } from './icons/search.js';
import note$ from './icons/note.js';
export { default as note } from './icons/note.js';
import shield$ from './icons/shield.js';
export { default as shield } from './icons/shield.js';
import dashboard$ from './icons/dashboard.js';
export { default as dashboard } from './icons/dashboard.js';
import graph$ from './icons/graph.js';
export { default as graph } from './icons/graph.js';
import settings$ from './icons/settings.js';
export { default as settings } from './icons/settings.js';
import project$ from './icons/project.js';
export { default as project } from './icons/project.js';
import play$ from './icons/play.js';
export { default as play } from './icons/play.js';
import githubAction$ from './icons/github-action.js';
export { default as githubAction } from './icons/github-action.js';
import code$ from './icons/code.js';
export { default as code } from './icons/code.js';
import gitBranch$ from './icons/git-branch.js';
export { default as gitBranch } from './icons/git-branch.js';
import diffAdded$ from './icons/diff-added.js';
export { default as diffAdded } from './icons/diff-added.js';
import diffIgnored$ from './icons/diff-ignored.js';
export { default as diffIgnored } from './icons/diff-ignored.js';
import diffModified$ from './icons/diff-modified.js';
export { default as diffModified } from './icons/diff-modified.js';
import diffRemoved$ from './icons/diff-removed.js';
export { default as diffRemoved } from './icons/diff-removed.js';
import diffRenamed$ from './icons/diff-renamed.js';
export { default as diffRenamed } from './icons/diff-renamed.js';
import diff$ from './icons/diff.js';
export { default as diff } from './icons/diff.js';
import circuitBoard$ from './icons/circuit-board.js';
export { default as circuitBoard } from './icons/circuit-board.js';
import gist$ from './icons/gist.js';
export { default as gist } from './icons/gist.js';
import gitCommit$ from './icons/git-commit.js';
export { default as gitCommit } from './icons/git-commit.js';
import gitCompare$ from './icons/git-compare.js';
export { default as gitCompare } from './icons/git-compare.js';
import gitMerge$ from './icons/git-merge.js';
export { default as gitMerge } from './icons/git-merge.js';
import gitPullRequest$ from './icons/git-pull-request.js';
export { default as gitPullRequest } from './icons/git-pull-request.js';
import issueClosed$ from './icons/issue-closed.js';
export { default as issueClosed } from './icons/issue-closed.js';
import issueOpened$ from './icons/issue-opened.js';
export { default as issueOpened } from './icons/issue-opened.js';
import issueReopened$ from './icons/issue-reopened.js';
export { default as issueReopened } from './icons/issue-reopened.js';
import database$ from './icons/database.js';
export { default as database } from './icons/database.js';
import noNewline$ from './icons/no-newline.js';
export { default as noNewline } from './icons/no-newline.js';
import broadcast$ from './icons/broadcast.js';
export { default as broadcast } from './icons/broadcast.js';
import keyboard$ from './icons/keyboard.js';
export { default as keyboard } from './icons/keyboard.js';
import fileBinary$ from './icons/file-binary.js';
export { default as fileBinary } from './icons/file-binary.js';
import fileCode$ from './icons/file-code.js';
export { default as fileCode } from './icons/file-code.js';
import fileDirectory$ from './icons/file-directory.js';
export { default as fileDirectory } from './icons/file-directory.js';
import fileMedia$ from './icons/file-media.js';
export { default as fileMedia } from './icons/file-media.js';
import filePdf$ from './icons/file-pdf.js';
export { default as filePdf } from './icons/file-pdf.js';
import fileSubmodule$ from './icons/file-submodule.js';
export { default as fileSubmodule } from './icons/file-submodule.js';
import fileSymlinkDirectory$ from './icons/file-symlink-directory.js';
export { default as fileSymlinkDirectory } from './icons/file-symlink-directory.js';
import fileSymlinkFile$ from './icons/file-symlink-file.js';
export { default as fileSymlinkFile } from './icons/file-symlink-file.js';
import fileZip$ from './icons/file-zip.js';
export { default as fileZip } from './icons/file-zip.js';
import browser$ from './icons/browser.js';
export { default as browser } from './icons/browser.js';
import file$ from './icons/file.js';
export { default as file } from './icons/file.js';
import repoClone$ from './icons/repo-clone.js';
export { default as repoClone } from './icons/repo-clone.js';
import repoForcePush$ from './icons/repo-force-push.js';
export { default as repoForcePush } from './icons/repo-force-push.js';
import repoForked$ from './icons/repo-forked.js';
export { default as repoForked } from './icons/repo-forked.js';
import repoPull$ from './icons/repo-pull.js';
export { default as repoPull } from './icons/repo-pull.js';
import repoPush$ from './icons/repo-push.js';
export { default as repoPush } from './icons/repo-push.js';
import repo$ from './icons/repo.js';
export { default as repo } from './icons/repo.js';
import mirror$ from './icons/mirror.js';
export { default as mirror } from './icons/mirror.js';
import ruby$ from './icons/ruby.js';
export { default as ruby } from './icons/ruby.js';
import server$ from './icons/server.js';
export { default as server } from './icons/server.js';
import terminal$ from './icons/terminal.js';
export { default as terminal } from './icons/terminal.js';
import radioTower$ from './icons/radio-tower.js';
export { default as radioTower } from './icons/radio-tower.js';
import rss$ from './icons/rss.js';
export { default as rss } from './icons/rss.js';
import versions$ from './icons/versions.js';
export { default as versions } from './icons/versions.js';
import requestChanges$ from './icons/request-changes.js';
export { default as requestChanges } from './icons/request-changes.js';
import squirrel$ from './icons/squirrel.js';
export { default as squirrel } from './icons/squirrel.js';
import zap$ from './icons/zap.js';
export { default as zap } from './icons/zap.js';
import flame$ from './icons/flame.js';
export { default as flame } from './icons/flame.js';
import bug$ from './icons/bug.js';
export { default as bug } from './icons/bug.js';
import person$ from './icons/person.js';
export { default as person } from './icons/person.js';
import smiley$ from './icons/smiley.js';
export { default as smiley } from './icons/smiley.js';
import hubot$ from './icons/hubot.js';
export { default as hubot } from './icons/hubot.js';
import thumbsdown$ from './icons/thumbsdown.js';
export { default as thumbsdown } from './icons/thumbsdown.js';
import thumbsup$ from './icons/thumbsup.js';
export { default as thumbsup } from './icons/thumbsup.js';
import organization$ from './icons/organization.js';
export { default as organization } from './icons/organization.js';
import gistSecret$ from './icons/gist-secret.js';
export { default as gistSecret } from './icons/gist-secret.js';
import eye$ from './icons/eye.js';
export { default as eye } from './icons/eye.js';
import eyeClosed$ from './icons/eye-closed.js';
export { default as eyeClosed } from './icons/eye-closed.js';
import jersey$ from './icons/jersey.js';
export { default as jersey } from './icons/jersey.js';
import octoface$ from './icons/octoface.js';
export { default as octoface } from './icons/octoface.js';
import markGithub$ from './icons/mark-github.js';
export { default as markGithub } from './icons/mark-github.js';
import logoGithub$ from './icons/logo-github.js';
export { default as logoGithub } from './icons/logo-github.js';
import logoGist$ from './icons/logo-gist.js';
export { default as logoGist } from './icons/logo-gist.js';
import markdown$ from './icons/markdown.js';
export { default as markdown } from './icons/markdown.js';
import paintcan$ from './icons/paintcan.js';
export { default as paintcan } from './icons/paintcan.js';

// This is auto-generated ES2015 icons from the modularize script. Please do not modify this file.

var icons = {};
icons.plus = plus$;
icons.primitiveDot = primitiveDot$;
icons.primitiveSquare = primitiveSquare$;
icons.quote = quote$;
icons.threeBars = threeBars$;
icons.triangleDown = triangleDown$;
icons.triangleLeft = triangleLeft$;
icons.triangleRight = triangleRight$;
icons.triangleUp = triangleUp$;
icons.kebabHorizontal = kebabHorizontal$;
icons.kebabVertical = kebabVertical$;
icons.screenFull = screenFull$;
icons.screenNormal = screenNormal$;
icons.x = x$;
icons.grabber = grabber$;
icons.plusSmall = plusSmall$;
icons.pulse = pulse$;
icons.star = star$;
icons.stop = stop$;
icons.sync = sync$;
icons.textSize = textSize$;
icons.report = report$;
icons.linkExternal = linkExternal$;
icons.checklist = checklist$;
icons.cloudDownload = cloudDownload$;
icons.cloudUpload = cloudUpload$;
icons.foldUp = foldUp$;
icons.foldDown = foldDown$;
icons.fold = fold$;
icons.tasklist = tasklist$;
icons.history = history$;
icons.dash = dash$;
icons.listOrdered = listOrdered$;
icons.listUnordered = listUnordered$;
icons.reply = reply$;
icons.mute = mute$;
icons.commentDiscussion = commentDiscussion$;
icons.comment = comment$;
icons.ellipsis = ellipsis$;
icons.heart = heart$;
icons.horizontalRule = horizontalRule$;
icons.info = info$;
icons.italic = italic$;
icons.unverified = unverified$;
icons.verified = verified$;
icons.question = question$;
icons.unfold = unfold$;
icons.signIn = signIn$;
icons.signOut = signOut$;
icons.alert = alert$;
icons.arrowDown = arrowDown$;
icons.arrowLeft = arrowLeft$;
icons.arrowRight = arrowRight$;
icons.arrowUp = arrowUp$;
icons.arrowBoth = arrowBoth$;
icons.arrowSmallDown = arrowSmallDown$;
icons.arrowSmallLeft = arrowSmallLeft$;
icons.arrowSmallRight = arrowSmallRight$;
icons.arrowSmallUp = arrowSmallUp$;
icons.check = check$;
icons.chevronDown = chevronDown$;
icons.chevronLeft = chevronLeft$;
icons.chevronRight = chevronRight$;
icons.chevronUp = chevronUp$;
icons.circleSlash = circleSlash$;
icons.bold = bold$;
icons.mention = mention$;
icons.beaker = beaker$;
icons.bell = bell$;
icons.briefcase = briefcase$;
icons.creditCard = creditCard$;
icons.deviceCameraVideo = deviceCameraVideo$;
icons.deviceCamera = deviceCamera$;
icons.deviceDesktop = deviceDesktop$;
icons.deviceMobile = deviceMobile$;
icons.gift = gift$;
icons.gear = gear$;
icons.book = book$;
icons.tag = tag$;
icons.telescope = telescope$;
icons.tools = tools$;
icons.trashcan = trashcan$;
icons.unmute = unmute$;
icons.watch = watch$;
icons.key = key$;
icons.archive = archive$;
icons.lightBulb = lightBulb$;
icons.link = link$;
icons.location = location$;
icons.lock = lock$;
icons.mailRead = mailRead$;
icons.mail = mail$;
icons.megaphone = megaphone$;
icons.bookmark = bookmark$;
icons.calendar = calendar$;
icons.clippy = clippy$;
icons.clock = clock$;
icons.desktopDownload = desktopDownload$;
icons.globe = globe$;
icons.home = home$;
icons.inbox = inbox$;
icons.law = law$;
icons.milestone = milestone$;
icons.mortarBoard = mortarBoard$;
icons.package = package$;
icons.pencil = pencil$;
icons.pin = pin$;
icons.plug = plug$;
icons.rocket = rocket$;
icons.search = search$;
icons.note = note$;
icons.shield = shield$;
icons.dashboard = dashboard$;
icons.graph = graph$;
icons.settings = settings$;
icons.project = project$;
icons.play = play$;
icons.githubAction = githubAction$;
icons.code = code$;
icons.gitBranch = gitBranch$;
icons.diffAdded = diffAdded$;
icons.diffIgnored = diffIgnored$;
icons.diffModified = diffModified$;
icons.diffRemoved = diffRemoved$;
icons.diffRenamed = diffRenamed$;
icons.diff = diff$;
icons.circuitBoard = circuitBoard$;
icons.gist = gist$;
icons.gitCommit = gitCommit$;
icons.gitCompare = gitCompare$;
icons.gitMerge = gitMerge$;
icons.gitPullRequest = gitPullRequest$;
icons.issueClosed = issueClosed$;
icons.issueOpened = issueOpened$;
icons.issueReopened = issueReopened$;
icons.database = database$;
icons.noNewline = noNewline$;
icons.broadcast = broadcast$;
icons.keyboard = keyboard$;
icons.fileBinary = fileBinary$;
icons.fileCode = fileCode$;
icons.fileDirectory = fileDirectory$;
icons.fileMedia = fileMedia$;
icons.filePdf = filePdf$;
icons.fileSubmodule = fileSubmodule$;
icons.fileSymlinkDirectory = fileSymlinkDirectory$;
icons.fileSymlinkFile = fileSymlinkFile$;
icons.fileZip = fileZip$;
icons.browser = browser$;
icons.file = file$;
icons.repoClone = repoClone$;
icons.repoForcePush = repoForcePush$;
icons.repoForked = repoForked$;
icons.repoPull = repoPull$;
icons.repoPush = repoPush$;
icons.repo = repo$;
icons.mirror = mirror$;
icons.ruby = ruby$;
icons.server = server$;
icons.terminal = terminal$;
icons.radioTower = radioTower$;
icons.rss = rss$;
icons.versions = versions$;
icons.requestChanges = requestChanges$;
icons.squirrel = squirrel$;
icons.zap = zap$;
icons.flame = flame$;
icons.bug = bug$;
icons.person = person$;
icons.smiley = smiley$;
icons.hubot = hubot$;
icons.thumbsdown = thumbsdown$;
icons.thumbsup = thumbsup$;
icons.organization = organization$;
icons.gistSecret = gistSecret$;
icons.eye = eye$;
icons.eyeClosed = eyeClosed$;
icons.jersey = jersey$;
icons.octoface = octoface$;
icons.markGithub = markGithub$;
icons.logoGithub = logoGithub$;
icons.logoGist = logoGist$;
icons.markdown = markdown$;
icons.paintcan = paintcan$;

export default icons;
